### ISSUE TITLE
fix (main) Makefile

### ISSUE THREAD

**Issue by pms967** [marcoc1712/squeezelite#2]
...so that it will accept "OPTS" also if "CFLAGS" is defined.

$ diff -u Makefile.orig Makefile

```
--- Makefile.orig       2017-02-28 23:56:49.239325357 +0100
+++ Makefile    2017-03-01 00:18:50.403288912 +0100
@@ -1,5 +1,6 @@
 # Cross compile support - create a Makefile which defines these three variables and then includes this Makefile...
-CFLAGS  ?= -Wall -fPIC -O2 $(OPTS)
+CFLAGS  ?= -Wall -fPIC -O2
+CFLAGS  += $(OPTS)
 LDFLAGS ?= -lasound -lpthread -lm -lrt
 EXECUTABLE ?= squeezelite-R2
```

**Comment by marcoc1712** [comment]
Not sure it will wors for all and any derived makefile.
But is s not even needed, because - as stated in the header - you could (and should)  create a makefile.xxx,, containing  CFLAGS, LDFLAGS, EXECUTABLE and eventually  OPTS definition  then include Makefile.

No needs to change, but of course you're welcome to use your own Makefile.

**Comment by pms967** [comment]
> Not sure it will wors for all and any derived makefile.

it will... ​why not?  The proposed modification does not really change anything in the behavior of the Makefile. If the other makefiles​ sets CFLAGS, LDFLAGS, etc, it will use them exactly as the old one.

The only difference is that with the mod you can set (independently) both CFLAGS and OPTS, while with the current one if you set CFLAGS, OPTS will be ignored. Which is an odd and counter-intuitive behavior.
