### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by olm52** [marcoc1712/squeezelite#7]
Archlinux package cannot be compiled any more. 
https://aur.archlinux.org/packages/squeezelite-r2-git/
Compilation was fine before with the following flags:
make CFLAGS='-Wall -fPIC -O2 -DLINUX -DALSA -DDSD -DFFMPEG -DRESAMPLE -DVISEXPORT'

A lot of errors about ffmpeg and dsd

Standard squeezelite-git package is compiling fine --> https://aur.archlinux.org/packages/squeezelite-git/

I guess something must be updated.

**Comment by marcoc1712** [comment]
HI,

I'm not the maintainer of the package, And I don't even know who made it. 
For what I could see in the dependency list FFmpeg is missing, don't really know if this could be the real cause. 

Sorry for that.

**Comment by marcoc1712** [comment]
-DFFMPEG option (among others)  is not supported by the package, please remove it and it is reported to work.

The R2 version is aimed to just reproduce PCM and DSD as a minimalist version, so most of the options introduced in squeezelite since 2006 are not supported, by design. The package should contain the MAKE file with the option to use, if not, please refer to the makefiles for Linux in the source directory.
